### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by Chatto** [StoryBox-dev/Frontend#10]
There should be a fixed Header and Footer, similar to the one I have on portal.risingtide.international. I was thinking that the Header would have perhaps a dropdown for selecting an active project on the left, and on the right,  Dashboard, Tasks, Posts(or Board), Files, and Logout. The Footer will have "My Profile, My Tasks, My Posts, and My Files.  This allows the user to see their own contributions to the projects, and the Header bit allows for navigation of the  active Project.
```
___________________________________________________________________________________________
StoryBox: [+Project]                     Dashboard :: Tasks :: Posts :: Files :: Logout
------------------------------------------------------------------------------------------
[Active Users]       |
                     |
                     |
                     |
                     |
                     |
                     |
                     |
-------------------------------------------------------------------------------------------
My Profile :: My Tasks :: My Posts :: My Files [Admin links if logged in as admin]
_____________________________________________________________________________________________
```

**Comment by BrandonDyer64** [comment]
As it stands, we have a sidebar that can be used for site navigation.

I don't see how changing this to a header/footer would help.

![image](https://user-images.githubusercontent.com/12021069/65255640-dc3d6600-dac3-11e9-81f9-ee0a6faaa3c3.png)

**Comment by Chatto** [comment]
Can we put that at the top and use this space for an online users list?

**Comment by BrandonDyer64** [comment]
Is an online users list important enough to take up that much screen real estate?

**Comment by MrNobodyX3** [comment]
Visually side panels give you more real estate (even if they don’t actually), a feeling of openness. More and more sites are moving towards side panels such as that. As top and bottom headers make you feel locked in, compressed, and not able to navigate smoothly. Having a sidebar also allows us the capability of creating a mobile version of the site with the same layout and navigation. By having it on the desktop version you ensured that desktop and mobile look the same and can be navigated the same way.

Top and bottom headers are also more common on text based websites such as blogs, news articles, or even social media like Facebook. And this is just visually to tell you when you have reached the end or if you're at the beginning. As far as I'm aware StoryBox will not need any large scale scrolling, so telling the user they’re at the start or end is not needed.
