### ISSUE TITLE
Sign In / Sign Up Page

### ISSUE THREAD

**Issue by BrandonDyer64** [StoryBox-dev/Frontend#3]
There needs to be a page for signing in and signing up.

This page doesn't yet need to be functional, but it does need to be visible.

**Comment by Chatto** [comment]
Yes, a simple page for sign in with a checkbox for "keep me signed in" and "remember login". I want the registration to be invite only, so perhaps a page where you can paste in an invite code.

**Comment by BrandonDyer64** [comment]
Registration will be site-wide, like Discord. Then you're invited to a space by an admin, or you can create your own (by either running a server, or buying a subscription)

**Comment by BrandonDyer64** [comment]
![image](https://user-images.githubusercontent.com/12021069/65271047-03a32b80-dae2-11e9-973c-ede045310e01.png)
