### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by BrandonDyer64** [StoryBox-dev/Frontend#5]
The default should still be a light theme, but there should be a nice big button to easily, and permanently, switch to a dark theme.

## Button Placement

There should be a button in the avatar profile drop-down, as well as in the footer.

## Style

This should change the styling as minimally as possible, only changing the base colors. It should allow for a complete UI overhaul without losing any theming.

## Code

The best way to achieve this, in my own opinion, is to create a modular theming system, with one file per theme. The button would then toggle between `default-light` and `default-dark`.

It should then be possible to add more theme options in the user settings, though this is out of the scope of this issue, and should be its own issue.

**Comment by Chatto** [comment]
Can we have a setting for background transparency value and dark/light theme toggle? You don't need much more customization than that!

**Comment by BrandonDyer64** [comment]
This doesn't apply anymore
