### ISSUE TITLE
Sidebar Background Image

### ISSUE THREAD

**Issue by BrandonDyer64** [StoryBox-dev/Frontend#8]
The sidebar should have a better background image. Something more related to game dev. It would also be nice if the image was rolling, so a different image was used every time you logged in or every day (not every page load).

**Comment by Chatto** [comment]
I was thinking user uploads their own background with a default image such as this for login and users without an uploaded background:
http://hinterlandroad.org:3000/assets/background.jpeg

Very RPG-ish, fitting to the name of StoryBox.
